--NUMEROS ALEATORIOS EM FLOAT
SELECT RAND()

--MOSTRA NUMEROS ALEATORIOS INTEIROS
SELECT ROUND(((500 - 100 - 1) * RAND() + 100), 0)
SELECT ROUND(((1000 - 1 - 1) * RAND() + 1), 0)

--FUNÇÃO QUE GERA NUMEROS ALEATORIOS
CREATE FUNCTION NumeroAleatorio (@VALOR_MINI INT, @VALOR_MAX INT)
RETURNS INT
AS
BEGIN
DECLARE @ALEATORIO INT
DECLARE @VALOR_ALEATORIO FLOAT
SELECT @VALOR_ALEATORIO = VALOR_ALEATORIO FROM VW_ALEATORIO
SET @ALEATORIO = ROUND(((@VALOR_MAX - @VALOR_MINI - 1) * @VALOR_ALEATORIO + @VALOR_MINI), 0)
RETURN @ALEATORIO
END;

SELECT dbo.[NumeroAleatorio](1,60)

--CRIANDO UMA MANEIRA DE USAR O RAND
CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS VALOR_ALEATORIO

SELECT * FROM VW_ALEATORIO